Get http://localhost:5003

###
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "PyaeSone123123@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "PyaeSone123123@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM2OTQyNjI0LCJleHAiOjE3MzcwMjkwMjR9.OqiZdUdbS45tfFmE0O38KJV2iyQ8WqMBHFTQXxefexg

###
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM2OTQyNjI0LCJleHAiOjE3MzcwMjkwMjR9.OqiZdUdbS45tfFmE0O38KJV2iyQ8WqMBHFTQXxefexg
Content-Type: application/json

{
    "task": "Finish coding the projects"
}

### Update a todo PUT /todos/:id (protected)
PUT http://localhost:5003/todos/1?task="thisistheupdated"
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM2OTQyNjI0LCJleHAiOjE3MzcwMjkwMjR9.OqiZdUdbS45tfFmE0O38KJV2iyQ8WqMBHFTQXxefexg
Content-Type: application/json

{
    "completed": 1
}

### Delete a todo PUT /todos/:id (protected)
DELETE http://localhost:5003/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM2OTQyNjI0LCJleHAiOjE3MzcwMjkwMjR9.OqiZdUdbS45tfFmE0O38KJV2iyQ8WqMBHFTQXxefexg
